### ISSUE TITLE
[Part 2 (a.i)] Create a spreadsheet detailing the list of M instructions.....

### ISSUE THREAD

**Issue by conneroisu** [conneroisu/processsor-proj-1#21]
The control signals excel sheet is required in the submission.
We should make sure to fill it out with all of the control signals that make up the process of understanding an assembly instruction

**Comment by aidanfoss** [comment]
[Part 2 (a.i)] Create a spreadsheet detailing the list of M instructions to be supported in your project alongside their binary opcodes and funct fields, if applicable. Create a separate column for each binary bit. Inside this spreadsheet, create a new column for the N control signals needed by your datapath implementation. The end result should be an N*M table where each row corresponds to the output of the control logic module for a given instruction.

**Comment by aidanfoss** [comment]
https://docs.google.com/spreadsheets/d/1Nnxoq6_Tk2c0i0f50bKNkF88FiopImRQ_nxxB89MChk/edit?usp=sharing
