### ISSUE TITLE
 In your writeup, explain how the right barrel shifter above can be enhanced to also support left shifting operations.

### ISSUE THREAD

**Issue by conneroisu** [conneroisu/processsor-proj-1#37]

**Comment by aidanfoss** [comment]
The final version of my barrel shifter already has this feature.

**Comment by aidanfoss** [comment]
working on this in 44-projectReportAidan

**Comment by aidanfoss** [comment]
![image](https://github.com/user-attachments/assets/fc83bca1-8386-405b-82e9-c3aec33064ff)

**Comment by aidanfoss** [comment]
![image](https://github.com/user-attachments/assets/073d2059-df10-4f8c-a61e-7ced09df2d21)
Code snippet could also be included directly below
