### ISSUE TITLE
Implement the control logic module using whatever method and coding style you prefer. Create a testbench to test this module individually, and show that your output matches the expected control signals from problem 1(a).

### ISSUE THREAD

**Issue by conneroisu** [conneroisu/processsor-proj-1#41]

**Comment by aidanfoss** [comment]
![image](https://github.com/user-attachments/assets/9dab5f37-6ab4-408d-ab03-a63045d80ab2)

**Comment by aidanfoss** [comment]
![image](https://github.com/user-attachments/assets/c9f5edfa-1deb-4955-b600-af47788f0c03)

**Comment by aidanfoss** [comment]
![image](https://github.com/user-attachments/assets/b9e2c7a8-896e-4629-9902-5facc5d66ac6)

**Comment by aidanfoss** [comment]
![image](https://github.com/user-attachments/assets/a57f5662-015f-4163-8297-1ee784ce1135)
