### ISSUE TITLE
[Part 2 (c.iii)] Draw a simplified, high-level schematic for the 32-bit ALU. Consider the following questions: how is Overflow calculated? How is Zero calculated? How is slt implemented?

### ISSUE THREAD

**Issue by conneroisu** [conneroisu/processsor-proj-1#47]
[Part 2 (c.iii)] 

[Part 2 (c.v)]

 
 
 Describe how the execution of the different operations corresponds to the Modelsim waveforms in your writeup.

**Comment by aidanfoss** [comment]
![image](https://github.com/user-attachments/assets/7d3ad624-c0d0-4a4f-904c-150b9616b9c7)
![image](https://github.com/user-attachments/assets/0be95bf7-4afd-4548-b6da-60fc32b0ed2d)

@DanielMauricio13 I added the waveform to the document
