### ISSUE TITLE
Synthesize Processor and commit results to the repo

### ISSUE THREAD

**Issue by conneroisu** [conneroisu/processsor-proj-1#51]

**Comment by aidanfoss** [comment]
could I get a better description of this? I'm not sure what this means.

**Comment by conneroisu** [comment]
Yeah sure. This means running the tool flow with documentation found in ./cpre381-toolflow.md
exerpt:
<exerpt>
Synthesis can be run via:
```zsh
./381_tf.sh synth
```

Synthesis output, such as timings files, can be found in the temp directory.
Be aware – synthesis may take several hours, particularly for Project 1.

</exerpt>

**Comment by conneroisu** [comment]
This should be for after we are sure that it works
