### ISSUE TITLE
[Part 2 (c.viii)] justify why your test plan is comprehensive. Include waveforms that demonstrate your test programs functioning.

### ISSUE THREAD

**Issue by conneroisu** [conneroisu/processsor-proj-1#54]
I think this is for the alu but double check

**Comment by aidanfoss** [comment]
@DanielMauricio13 justified how the tests were working

**Comment by conneroisu** [comment]
Is this done?

**Comment by aidanfoss** [comment]
@DanielMauricio13 i believe justified the tests, not sure on completion

**Comment by DanielMauricio13** [comment]
I must adding new detailed tests
